<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="crawler">

  <!--
        To generate the correct .URDF from this XACRO file see https://answers.ros.org/question/10401/how-to-convert-xacro-file-to-urdf-file/
  -->

  <!--CONSTANTS-->
  <xacro:property name="PI" value="3.14159" />

  <xacro:property name="BODY_LENGTH" value="0.76"/>
  <xacro:property name="BODY_MASS" value="2.8"/>

  <xacro:property name="SPINE_SEGMENTS_NUMBER" value="5" />
  <xacro:property name="N_HALF" value="3" />

  <xacro:property name="SPINE_SEGMENT_LENGTH" value="${BODY_LENGTH/(SPINE_SEGMENTS_NUMBER+1)}" />
  <xacro:property name="SPINE_DORSAL_BENDING_LIMIT" value="${PI/8}" />
  <xacro:property name="SPINE_LATERAL_BENDING_LIMIT" value="${PI/2}" />

  <xacro:property name="BODY_SPHERE_MASS" value="${BODY_MASS/(SPINE_SEGMENTS_NUMBER+2)}" /><!-- +2 for the girdle masses-->
  <xacro:property name="BODY_SPHERE_RADIUS" value="${BODY_LENGTH/16}" />
  <xacro:property name="BODY_SPHERE_INERTIA" value="${2*BODY_SPHERE_MASS*BODY_SPHERE_RADIUS*BODY_SPHERE_RADIUS/5}" />

  <xacro:property name="GIRDLE_WIDTH" value="${BODY_LENGTH/14}" />
  <xacro:property name="GIRDLE_LENGTH" value="${SPINE_SEGMENT_LENGTH/2}" />

  <xacro:property name="LEG_LENGTH" value="${BODY_LENGTH/9.4}" />
  <xacro:property name="LEG_TIP_MASS" value="${BODY_SPHERE_MASS/10}" />
  <xacro:property name="LEG_TIP_RADIUS" value="${BODY_SPHERE_RADIUS/3}" />
  <xacro:property name="LEG_TIP_INERTIA" value="${2*LEG_TIP_MASS*LEG_TIP_RADIUS*LEG_TIP_RADIUS/5}" />

  <xacro:property name="GIRDLE_FLEXION_LIMIT" value="${PI/6}" />
  <xacro:property name="GIRDLE_EXTENSION_LIMIT" value="${PI/6}" />

  <xacro:property name="GIRDLE_ABDUCTION_LIMIT" value="${PI/2}" />
  <xacro:property name="GIRDLE_ADDUCTION_LIMIT" value="${PI/2}" />

  <xacro:property name="JOINT_DAMPING" value="0.0" />
  <xacro:property name="JOINT_FRICTION" value="0.0" />
  <xacro:property name="JOINT_MAX_SPEED" value="50.0" />
  <xacro:property name="JOINT_MAX_EFFORT" value="50.0" />


  <xacro:property name="VISUAL_BOX_RATIO" value="0.05" />


<!--########### COLORS used for the links ###########-->
<!--colors are currently implemented as macro because just defining them, as shown in the ROS tutorial, seems not to work-->
  
  <material name="girdle_material">
    <color rgba="0.106 0.6 0.545 1"/>
  </material>
  <material name="body_material">
    <color rgba="1 0.8235 0.298 1"/>
  </material>
  <material name="leg_material">
    <color rgba="0.878 0.471 0.333 1"/>    
  </material>

<!--########### MACRO for links and joints ###########-->

  <xacro:macro name="spine_segment_macro" params="N">
    <link name="spine_connection_${N}">
      <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${BODY_SPHERE_MASS/100}"/>
        <inertia ixx="${BODY_SPHERE_INERTIA/100}"  ixy="0"  ixz="0" iyy="${BODY_SPHERE_INERTIA/100}" iyz="0" izz="${BODY_SPHERE_INERTIA/100}" />
      </inertial>
    </link>
    <link name="spine_link_${N}">
      <inertial>
      <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
        <mass value="${BODY_SPHERE_MASS}"/>
        <inertia ixx="${BODY_SPHERE_INERTIA}"  ixy="0"  ixz="0" iyy="${BODY_SPHERE_INERTIA}" iyz="0" izz="${BODY_SPHERE_INERTIA}" />
      </inertial>
      <visual>
        <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${BODY_SPHERE_RADIUS}" />
        </geometry>
        <material name="body_material"/>
      </visual>
      <visual>
        <origin xyz="${-SPINE_SEGMENT_LENGTH/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${SPINE_SEGMENT_LENGTH} ${VISUAL_BOX_RATIO*SPINE_SEGMENT_LENGTH} ${VISUAL_BOX_RATIO*SPINE_SEGMENT_LENGTH}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${BODY_SPHERE_RADIUS}" />
        </geometry>
      </collision>
    </link>
    <joint name="spine_lateral_joint_${N}" type="revolute">
      <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <parent link="spine_link_${N-1}"/>
      <child link="spine_connection_${N}"/>
      <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
      <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${SPINE_LATERAL_BENDING_LIMIT}" upper="${SPINE_LATERAL_BENDING_LIMIT}" />
    </joint>
    <joint name="spine_dorsal_joint_${N}" type="revolute">
      <origin xyz="0 0 0" rpy="${-PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <parent link="spine_connection_${N}"/>
      <child link="spine_link_${N}"/>
      <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
      <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${SPINE_DORSAL_BENDING_LIMIT}" upper="${SPINE_DORSAL_BENDING_LIMIT}" />
    </joint>
  </xacro:macro>

  <xacro:macro name="leg_macro" params="prefix reflect">
    <link name="${prefix}_girdle_connection_1">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${LEG_TIP_MASS/100}"/>
        <inertia ixx="${LEG_TIP_INERTIA/100}"  ixy="0"  ixz="0" iyy="${LEG_TIP_INERTIA/100}" iyz="0" izz="${LEG_TIP_INERTIA/100}" />
      </inertial>
    </link>
    <!--NOTE: currently leg joints have symmetrical limits, to avoid problems deriving from having reflected reference frames-->
    <joint name="${prefix}_girdle_abduction_joint" type="revolute">
      <origin xyz="0 ${-reflect*GIRDLE_WIDTH} 0" rpy="0 0 ${-reflect*PI/2}"/>
      <axis xyz="0 0 1"/>
      <parent link="girdle"/>
      <child link="${prefix}_girdle_connection_1"/>
      <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
      <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${GIRDLE_ABDUCTION_LIMIT}" upper="${GIRDLE_ABDUCTION_LIMIT}" />
    </joint>
    <link name="${prefix}_leg">
      <inertial>
      <origin xyz="${LEG_LENGTH} 0 0" rpy="0 0 0"/>
        <mass value="${LEG_TIP_MASS}"/>
        <inertia ixx="${LEG_TIP_INERTIA}"  ixy="0"  ixz="0" iyy="${LEG_TIP_INERTIA}" iyz="0" izz="${LEG_TIP_INERTIA}" />
      </inertial>
      <visual>
        <origin xyz="${LEG_LENGTH} 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${LEG_TIP_RADIUS}" />
        </geometry>
        <material name="leg_material"/>
      </visual>
      <visual>
        <origin xyz="${LEG_LENGTH/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${LEG_LENGTH} ${VISUAL_BOX_RATIO*LEG_LENGTH} ${VISUAL_BOX_RATIO*LEG_LENGTH}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${LEG_LENGTH} 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${LEG_TIP_RADIUS}" />
        </geometry>
      </collision>
    </link>
    <!--NOTE: currently leg joints have symmetrical limits, to avoid problems deriving from having reflected reference frames-->
    <joint name="${prefix}_girdle_flection_joint" type="revolute">
      <origin xyz="0 0 0" rpy="${-reflect*PI/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <parent link="${prefix}_girdle_connection_1"/>
      <child link="${prefix}_leg"/>
      <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
      <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${GIRDLE_FLEXION_LIMIT}" upper="${GIRDLE_FLEXION_LIMIT}" />
    </joint>
  </xacro:macro>

  <!-- Loop is off by one because the first segment is added manually -->
  <xacro:macro name="spine_segments_loop" params="segments_qty">
    <xacro:spine_segment_macro N="${SPINE_SEGMENTS_NUMBER + 2 - segments_qty}"/>
    <xacro:if value="${segments_qty-2}">
        <xacro:spine_segments_loop segments_qty="${segments_qty-1}" />
    </xacro:if>
  </xacro:macro>


<!-- ########### MODEL LINKS AND JOINTS ########### -->
  <link name="girdle">
   <inertial>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <mass value="${2*BODY_SPHERE_MASS}"/>
     <inertia ixx="${2*BODY_SPHERE_INERTIA}"  ixy="0"  ixz="0" 
              iyy="${2*(BODY_SPHERE_INERTIA+GIRDLE_LENGTH*GIRDLE_LENGTH*BODY_SPHERE_MASS)}" iyz="0" 
              izz="${2*(BODY_SPHERE_INERTIA+GIRDLE_LENGTH*GIRDLE_LENGTH*BODY_SPHERE_MASS)}" />
   </inertial>
   <visual>
     <origin xyz="${GIRDLE_LENGTH} 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${BODY_SPHERE_RADIUS}" />
     </geometry>
     <material name="girdle_material"/>
   </visual>
   <visual>
     <origin xyz="${-GIRDLE_LENGTH} 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${BODY_SPHERE_RADIUS}" />
     </geometry>
   </visual>
   <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="${VISUAL_BOX_RATIO*2*GIRDLE_WIDTH} ${2*GIRDLE_WIDTH} ${VISUAL_BOX_RATIO*2*GIRDLE_WIDTH}"/>
     </geometry>
   </visual>
   <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="${2*GIRDLE_LENGTH} ${VISUAL_BOX_RATIO*2*GIRDLE_LENGTH} ${VISUAL_BOX_RATIO*2*GIRDLE_LENGTH}"/>
     </geometry>
   </visual>
   <collision>
     <origin xyz="${GIRDLE_LENGTH} 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${BODY_SPHERE_RADIUS}" />
     </geometry>
   </collision>
   <collision>
     <origin xyz="${-GIRDLE_LENGTH} 0 0" rpy="0 0 0"/>
     <geometry>
       <sphere radius="${BODY_SPHERE_RADIUS}" />
     </geometry>
   </collision>
 </link>

  <link name="spine_connection_1">
      <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${BODY_SPHERE_MASS/100}"/>
        <inertia ixx="${BODY_SPHERE_INERTIA/100}"  ixy="0"  ixz="0" iyy="${BODY_SPHERE_INERTIA/100}" iyz="0" izz="${BODY_SPHERE_INERTIA/100}" />
      </inertial>
    </link>
  <link name="spine_link_1">
    <inertial>
    <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
      <mass value="${BODY_SPHERE_MASS}"/>
      <inertia ixx="${BODY_SPHERE_INERTIA}"  ixy="0"  ixz="0" iyy="${BODY_SPHERE_INERTIA}" iyz="0" izz="${BODY_SPHERE_INERTIA}" />
    </inertial>
    <visual>
      <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${BODY_SPHERE_RADIUS}" />
      </geometry>
      <material name="body_material"/>
    </visual>
    <visual>
      <origin xyz="${-SPINE_SEGMENT_LENGTH/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${SPINE_SEGMENT_LENGTH} ${VISUAL_BOX_RATIO*SPINE_SEGMENT_LENGTH} ${VISUAL_BOX_RATIO*SPINE_SEGMENT_LENGTH}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="${-SPINE_SEGMENT_LENGTH} 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${BODY_SPHERE_RADIUS}" />
      </geometry>
    </collision>
  </link>
  <joint name="spine_lateral_joint_1" type="revolute">
    <origin xyz="${-GIRDLE_LENGTH} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="girdle"/>
    <child link="spine_connection_1"/>
    <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
    <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${SPINE_LATERAL_BENDING_LIMIT}" upper="${SPINE_LATERAL_BENDING_LIMIT}" />
  </joint>
  <joint name="spine_dorsal_joint_1" type="revolute">
    <origin xyz="0 0 0" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="spine_connection_1"/>
    <child link="spine_link_1"/>
    <dynamics damping="${JOINT_DAMPING}" friction="${JOINT_FRICTION}"/>
    <limit effort="${JOINT_MAX_EFFORT}" velocity="${JOINT_MAX_SPEED}" lower="-${SPINE_DORSAL_BENDING_LIMIT}" upper="${SPINE_DORSAL_BENDING_LIMIT}" />
  </joint>

  <xacro:spine_segments_loop segments_qty="${SPINE_SEGMENTS_NUMBER}"/>

  <xacro:leg_macro prefix="right" reflect="1"/>
  <xacro:leg_macro prefix="left" reflect="-1"/>

</robot>